/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGrado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtFuncion = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lagrange");

        jLabel2.setText("Grado:");

        tablaArea.setColumns(20);
        tablaArea.setRows(5);
        jScrollPane1.setViewportView(tablaArea);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtFuncion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "X", "Y"
            }
        ));
        jScrollPane2.setViewportView(jtFuncion);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addComponent(txtGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(btnCrear)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*interpolacionLagrange(Integer.parseInt(this.txtGrado.getText()),
                Integer.parseInt(this.txtGrado.getText()),
                Integer.parseInt(this.txtGrado.getText()));*/
        tablaArea.append("METODO DE LAGRANGE");
        int g=Integer.parseInt(txtGrado.getText());
        g=g+1;
        String nue4 = JOptionPane.showInputDialog("INGRESE UN PUNTO X PARA ENCONTRAR EL VALOR DE F(X) ");
        double x = Double.parseDouble(nue4);
        double v[]=new double[g];
        double v1[]=new double[g];
        int g1=g+1;
        double m[][]=new double[g][g1];
        for(int i=0;i<g;i++){
           for(int j=0;j<2;j++){
               if(j==0){
                   v[i]=Double.parseDouble(jtFuncion.getValueAt(i,j).toString());
               }else{
                    v1[i]=Double.parseDouble(jtFuncion.getValueAt(i,j).toString());
                }
            }
        }
        
        DecimalFormat f=new DecimalFormat("0.0000");
        String resultadoFuncion = "";
        double resultado = 0;
        int n = v.length;
        
        for (int i = 0; i < n; i++) {
        double termino = v1[i];
        String terminoFuncion = f.format(termino);
        for (int j = 0; j < n; j++) {
            if (i != j) {
            termino *= (x - v[j]) / (v[i] - v[j]);
            terminoFuncion += "*(x-" + f.format(v[j]) + ")/(" + f.format(v[i]) + "-" + f.format(v[j]) + ")";
            }
        }
            resultadoFuncion += terminoFuncion + " + ";
        }
        resultadoFuncion = resultadoFuncion.substring(0, resultadoFuncion.length() - 3); // quitar el último "+"
        
        StringBuffer funcionInterpolante = new StringBuffer();
        for (int i = 0; i < n; i++) {
            double terminoNumerador = v1[i];
            double terminoDenominador = 1;
            for (int j = 0; j < n; j++) {
                if (i != j) {
                    terminoNumerador *= (x - v[j]);
                    terminoDenominador *= (v[i] - v[j]);
                }
            }
            String fraccion = "(" + terminoNumerador + ")/(" + terminoDenominador + ")";
            funcionInterpolante.append(fraccion);
            if (i < n - 1) {
                funcionInterpolante.append(" + ");
            }
        }
        //tablaArea.append("\n La funcion interpolante es: " + funcionInterpolante.toString());
        
        for (int i = 0; i < n; i++) {
            double termino = v1[i];
            for (int j = 0; j < n; j++) {
                if (i != j) {
                    termino *= (x - v[j]) / (v[i] - v[j]);
                }
            }
            resultado += termino;
            System. out. println(resultado); 
        }
        //System. out. println(resultado);
        //tablaArea.append("\nLa función es: F(x) = " + resultadoFuncion);
        tablaArea.append("\n La funcion interpolante es: " + funcionInterpolante.toString());
        tablaArea.append("\nEl resultado con F(x)= "+x+" es: "+resultado);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtFuncion.getModel();
        int g=Integer.parseInt(this.txtGrado.getText());
        g=g+1;
        model.setRowCount(g);
        model.setColumnCount(2);
       
    }//GEN-LAST:event_btnCrearActionPerformed
    
    private double interpolacionLagrange2(double[] v, double[] v1, double x) {
        double resultado = 0;
        int n = v.length;
        for (int i = 0; i < n; i++) {
            double termino = v1[i];
            for (int j = 0; j < n; j++) {
                if (i != j) {
                    termino *= (x - v[j]) / (v[i] - v[j]);
                }
            }
            resultado += termino;
        }
        System. out. println(resultado);
        return resultado;
    }
    
    
    
    private String interpolacionLagrange(int grado, double[] x, double[] y) {
        double[] l = new double[grado + 1];
        double[] p = new double[grado + 1];
        double[] f = new double[grado + 1];
        double s;

        for (int i = 0; i <= grado; i++) {
            l[i] = 1;
            for (int j = 0; j <= grado; j++) {
                if (j != i) {
                    l[i] *= (x[i] - x[j]);
                }
            }
            l[i] = y[i] / l[i];
        }

        for (int i = 0; i <= grado; i++) {
            p[0] += l[i];
        }

        for (int k = 1; k <= grado; k++) {
            for (int i = k; i <= grado; i++) {
                f[i] = (p[i] - p[i - 1]) / (x[i] - x[i - k]);
            }

            for (int i = k; i <= grado; i++) {
                p[i] = f[i];
            }
        }

        String resultado = "";
        for (int i = 0; i <= grado; i++) {
            resultado += String.format("%.4f", p[i]) + " ";
            for (int j = 0; j <= grado; j++) {
                if (j != i) {
                    resultado += String.format("(x - %.4f) / (%.4f - %.4f) ", x[j], x[i], x[j]);
                }
            }
            resultado += "+ ";
        }
        resultado = resultado.substring(0, resultado.length() - 2); // Eliminar el último "+ "
        System. out. println(resultado);
        
        return resultado;
    }
    
    private boolean validarTabla(double[] x, double[] y) {
        if (x.length != y.length) {
            return false; 
         }
        for (int i = 0; i < x.length; i++) {
            for (int j = i + 1; j < x.length; j++) {
                if (x[i] == x[j]) {
                    return false;
                }
            }
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCrear;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jtFuncion;
    public javax.swing.JTextArea tablaArea;
    public javax.swing.JTextField txtGrado;
    // End of variables declaration//GEN-END:variables
}
